### ISSUE TITLE
Add a menu button (for devices without dedicated menu button)

### ISSUE THREAD

**Issue by jschaeke** [domogik/domodroid#100]
My tablet does not have a dedicated menu button (only back, home and task list), so I can't go into the configuration menu. Unfortunately, I can't use soft floating buttons to emulate a menu button (root required). This makes domodroid to be non-functional.

**Comment by tikismoke** [comment]
Could yout tell me the version of your tablet?
They're is a way to open menu but it dépends on each vendor.

**Comment by tikismoke** [comment]
For example try this: http://android.stackexchange.com/a/81598

**Comment by jschaeke** [comment]
A teclast x98 air ii, running a custom build (aosp). Yes and I tried the long-press method on the task list.
Unfortunately, rooting it is rather complex, so I'd rather postpone it...

**Comment by jschaeke** [comment]
http://forum.xda-developers.com/x98-air/themes-apps/navibar-3-5-7-buttons-mod-android-5-0-t3269680
Found it for my rom...

**Comment by tikismoke** [comment]
This sould be solved when #32 will be solved, but it is still not for now.

**Comment by jschaeke** [comment]
In the end, I solved by getting root and installing this (Iput it herebfor reference):
https://play.google.com/store/apps/details?id=com.gmd.hidesoftkeys

**Comment by tikismoke** [comment]
Happy to know that. It's indeed a solution for root device.
But the best will be with actionbar drawer (swappable from left for example).
So much to do :(

I permit to close as it is solved for you and still in the dodo with #32.

**Comment by tikismoke** [comment]
@jschaeke Could you send me your mail at new.domodroid at gmail.com
I have a version you could test to tell me if menu button is present on top.
