### ISSUE TITLE
Préférences order

### ISSUE THREAD

**Issue by tikismoke** [domogik/domodroid#108]
Put debug to end.
Reorder it by gravity emergency.

**Comment by fritz-smh** [comment]
Maybe also add some preferences (log config) in a sub menu ?

**Comment by tikismoke** [comment]
@fritz-smh you mean like this: https://developer.android.com/guide/topics/ui/settings.html#Subscreens

**Comment by fritz-smh** [comment]
yes

**Comment by tikismoke** [comment]
@fritz_smh think we can close this one no?
