### ISSUE TITLE
Unable to sync domodroid (AUTH not working)

### ISSUE THREAD

**Issue by overload08** [domogik/domodroid#133]
Quand j'essaie de synchroniser domodroid, il me dit qu'il ne peut pas charger la liste des device.

Domodroid v25
Domogik v0.5.0

Quand je tente d'aller sur l'URL http://admin:123@10.0.101.25/rest/device/ : 
"Could not verify your access level for that URL.\n You have to login with proper credentials."

**Comment by tikismoke** [comment]
Ok c'est peut-être mal expliqué dans la Doc.

Dans domogik admin tu as bien admin/123
Mais pour rest pas sur que tu l'ais activé dans la conf de domogik.

Donc essaye sans user/password pour voir.

Il faut distinguer l'autentification de l'admin de celle de rest.

Tiens moi au jus.

**Comment by overload08** [comment]
Avec ou sans c'est pareil...
Dans les traces que j'ai capturées, je ne vois pas domodroid envoyer les login/password
Bug d'authentification ?

**Comment by tikismoke** [comment]
Je fini un truc et j'arrive sur IRC pour voir ça ensemble. Normalement l'authentification était OK.

Peut-être une régression côté dmd :(

**Comment by overload08** [comment]
Ca marche.

Je te mets les traces au cas où


GET /rest/ HTTP/1.1
Host: 10.0.101.25:40406
Connection: Keep-Alive

HTTP/1.1 200 OK
Content-Length: 434
Content-Type: application/json
Server: TornadoServer/4.2

{
    "info": {
        "Domogik_release": "0.5.0", 
        "Domogik_version": "0.5.0", 
        "Host": "gidomogik", 
        "REST_API_release": "0.8", 
        "REST_API_version": "0.8", 
        "SSL": "False", 
        "Sources_release": "0.5.0", 
        "Sources_version": "0.5.0"
    }, 
    "mq": {
        "ip": "0.0.0.0", 
        "pub_port": "40411", 
        "req_rep_port": "40410", 
        "sub_port": "40412"
    }
}

GET /rest/device HTTP/1.1
Host: 10.0.101.25:40406
Connection: Keep-Alive

HTTP/1.1 301 MOVED PERMANENTLY
Content-Length: 281
Content-Type: text/html; charset=utf-8
Location: http://10.0.101.25:40406/rest/device/
Server: TornadoServer/4.2

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to target URL: <a href="http://10.0.101.25:40406/rest/device/">http://10.0.101.25:40406/rest/device/</a>.  If not click the link.

GET /rest/device/ HTTP/1.1
Host: 10.0.101.25:40406
Connection: Keep-Alive

HTTP/1.1 401 UNAUTHORIZED
Content-Length: 95
Content-Type: application/json
Server: TornadoServer/4.2

"Could not verify your access level for that URL.\n You have to login with proper credentials."
