### ISSUE TITLE
Other app for Domodroid

### ISSUE THREAD

**Issue by Poussinou** [domogik/domodroid#160]
Hi @domogik
Is [this](https://play.google.com/store/apps/details?id=co.Black.android68) an old version of your app, or something completely new?

**Comment by tikismoke** [comment]
Hi good find, I'm going to make test and let you know. I thinks it's an old version but maybe with extra features after all it's free ;)

If it's a bad apps (malware) I'll made the request to Google to remove it from the store.

Thank's for this find

Le 30 août 2017 16:09:06 GMT+02:00, Poussinou <notifications@github.com> a écrit :
>Hi @domogik
>Is
>[this](https://play.google.com/store/apps/details?id=co.Black.android68)
>an old version of your app, or something completely new?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domodroid/issues/160

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Poussinou** [comment]
If this is an old version, please fill in the DCMA takedown request [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay).
[All his apps](https://play.google.com/store/apps/developer?id=Pham+Quynh+Android) are open-sourced apps which he hijacked and stole...

**Comment by tikismoke** [comment]
Yes but domodroid is free. At what point can we forbid this practice?
Need to have teams point of view too.
@fritzsmh @cerealnd

**Comment by Poussinou** [comment]
He doesn't respect the GNU GPL v3 at all. But since it's your app, you are free not to report him ;)

**Comment by tikismoke** [comment]
We are looking at this problems with Domogik team.

Personally I do not really know what's the good approach :(

**Comment by fritz-smh** [comment]
@Poussinou what makes you tell that he does not respect the license ?

(I am quite busy on my side so I didn't look closely)

**Comment by Cereal2nd** [comment]
i looked at it, and there is no reference back to the original domodroid,
so its not respecting the license

**Comment by tikismoke** [comment]
Ok i'll done the Both DCMA and inapropriate content on play store.

Not sure it will do anything but i've tried.

**Comment by Poussinou** [comment]
He doesn't respect the license because : 
* He doesn't provide the link to the source code;
* He doesn't publish the changes he made (the name of the app for example...);
* He doesn't specify that the source code of the app is licensed under GPL v3

These are the terms of the GNU GPL v3 ;)

Google will maybe ask you some details, or maybe a screenshot of your own app. Give them a screenshot of the right old version of your app...

**Comment by tikismoke** [comment]
Bonjour,

Merci de votre réclamation ci-jointe.

Concernant les URL suivantes:

https://play.google.com/store/apps/details?id=co.Black.android68
https://play.google.com/store/apps/details?id=org.domogik.domodroid13&hl=fr

Il s'avère que le contenu en question n'est pas conforme à notre règlement. Nous sommes donc en train de le supprimer de nos services.

Cordialement,
L'équipe Google

I've checked seems the other apps is no more available :)

**Comment by Poussinou** [comment]
Good we can close now :)
