### ISSUE TITLE
Enchancement : Have the possibility to use dns name for MQ configuration

### ISSUE THREAD

**Issue by jaywax** [domogik/domodroid#162]
Hi,
Could be nice if we could use dns names for configuring MQ Address.
Thanks.

version : domodroid13 1.4_android_sudio Rev_33

**Comment by jaywax** [comment]
Sorry, bad configuration on my side...

**Comment by tikismoke** [comment]
Non problem, i was asking why or should Not work.

Remember it will Not been used outsider local wifi (the mq).

Ans to avoir typo problème. You could use the qrcode to configure dmd.

**Comment by jaywax** [comment]
My configuration is a little bit tricky : 
Rest is joignable behing a loadbalancer and a cluster of ssl nginx server under certain dns name (let's say https://domogik.local) and MQ just behind the loadbalancer, accessible by another dns names (let's say domotique.local).
