### ISSUE TITLE
Question : Possible to connect under vpn ?

### ISSUE THREAD

**Issue by jaywax** [domogik/domodroid#164]
Hi,
I'm trying to connect (through ipsec vpn under wan ip) to my domogik server. The vpn part is ok and i can reach all my others lan services when my vpn is up, but i can't still connect (i don't see any traffic on my firewall). Due to the work done, i think it's a normal behavior. Can you confirm ? 

French : 
Hello, j'essaye de me connecter via un vpn ipsec depuis mon tél android à mon serveur domogik via domodroid. Je sais que pas mal de travail a été fait pour éviter les connexions lorsqu'on est pas en wifi (d'ailleurs je confirme, il n'y a rien qui part du téléhpone :p). Peux-tu confirmer que c'est normal que je ne vois rien sortir du téléphone, une fois connecter au vpn ?

Merci.

**Comment by tikismoke** [comment]
Tu devrais quand même avoir le gilet toutes les xx minutes qui essaye de rechopper les stats. Après effectivement même en vpn du coup t'es pas sur le bon réseau wifi donc la maison sera HS.

Le 2 novembre 2017 17:33:52 GMT+01:00, jaywax <notifications@github.com> a écrit :
>Hi,
>I'm trying to connect (through ipsec vpn under wan ip) to my domogik
>server. The vpn part is ok and i can reach all my others lan services
>when my vpn is up, but i can't still connect (i don't see any traffic
>on my firewall). Due to the work done, i think it's a normal behavior.
>Can you confirm ? 
>
>French : 
>Hello, j'essaye de me connecter via un vpn ipsec depuis mon tél android
>à mon serveur domogik via domodroid. Je sais que pas mal de travail a
>été fait pour éviter les connexions lorsqu'on est pas en wifi
>(d'ailleurs je confirme, il n'y a rien qui part du téléhpone :p).
>Peux-tu confirmer que c'est normal que je ne vois rien sortir du
>téléphone, une fois connecter au vpn ?
>
>Merci.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domodroid/issues/164

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by jaywax** [comment]
Merci pour ta réponse. 
En fait quand j'essaye de me connecter, il me dit "unknown host", idem pour la synchronisation. Même pas une petite requête dns avec le fqdn du host configuré dans domodroid...

**Comment by jaywax** [comment]
Une maison doit être associée à un seul réseaux wifi pour que cela fonctionne ?

**Comment by tikismoke** [comment]
Fait moi un ticket je regarderai dans le weekend si je trouve le temps. Désolé c'est chaud encore jusqu'à Noël, entre le taf et la maison. Et sans vpn tout fonctionne ?

Le 2 novembre 2017 17:42:37 GMT+01:00, jaywax <notifications@github.com> a écrit :
>Merci pour ta réponse. 
>En fait quand j'essaye de me connecter, il me dit "unknown host", idem
>pour la synchronisation. Même pas une petite requête dns avec le fqdn
>du host configuré dans domodroid...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domodroid/issues/164#issuecomment-341483445

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tikismoke** [comment]
Oui :( j'ai pas trouvé mieux pour le moment...

Le 2 novembre 2017 17:43:29 GMT+01:00, jaywax <notifications@github.com> a écrit :
>Une maison doit être associée à un seul réseaux wifi pour que cela
>fonctionne ?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domodroid/issues/164#issuecomment-341483740

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by jaywax** [comment]
Te prends pas le choux, je peux toujours me connecter via domoweb (moins sexy depuis un téléphone, mais pas de soucis côté vpn). 
Je te fais un ticket pour éventuellement pouvoir se connecter un jour par vpn, mais je suis conscient que ca va générer un peu de taf en profondeur...

**Comment by jaywax** [comment]
see  #158
