### ISSUE TITLE
DT_OpenClose widget in 0.4

### ISSUE THREAD

**Issue by tikismoke** [domogik/domodroid#53]
In widget the animation representation for close say on an open off (state is correct open/close)
But if you select the door, window or portal icon is representation will be ok.

**Comment by fritz-smh** [comment]
And the status on or off on the right should be replaced by the real value : close or open ;)

**Comment by tikismoke** [comment]
Will remove it as command can't not know sensor status for the moment.

**Comment by tikismoke** [comment]
The on off state on right is an image...

Need to adapt the right part to a background and a text.
