### ISSUE TITLE
screenshot of weather forecast

### ISSUE THREAD

**Issue by axboct** [domogik/domodroid#67]
![screenshot_2015-12-13-14-01-34](https://cloud.githubusercontent.com/assets/11463718/11766907/72f95bb6-a1a3-11e5-8042-e1ee3b36efc0.png)

**Comment by tikismoke** [comment]
https://github.com/domogik/domodroid/commit/e7ca95f09668fd7b83929184dd3b00e8183d5380

Need to make a pass, some string have disappear from source somewhere :(
