### ISSUE TITLE
Missing build.gradle file?

### ISSUE THREAD

**Issue by krt16s** [domogik/domodroid#82]
It looks like `Domodroid/build.gradle` is missing?

**Comment by tikismoke** [comment]
Hope it will make it working on F-Droid as some user want it to be present on it ;)

**Comment by krt16s** [comment]
Doesn't look like you added the file. There should be a `./build.gradle`, a `./settings.gradle` and a `./Domodroid/build.gradle`

**Comment by tikismoke** [comment]
Ok they are in gitignore normally. I push them later.
Thank's by advance for our user.

**Comment by tikismoke** [comment]
I do not have `./Domodroid/build.gradle` on my machine.

Those the last push is enough?

**Comment by krt16s** [comment]
I don't know where your local build or AndroidStudio are getting its build information from, but I cannot run `gradle clean` or `gradle assembleRelease` on a clean checkout. The build file is storing information on used repositories, dependencies and buildtools, so it's necessary.

**Comment by tikismoke** [comment]
Sorry i migrate from Ant and Eclipse only few month ago.
I'll have to investigate this part as I don't understand it at all.
I create #84 to make more test on distant build system indeed.
I'll make you know when it will be Ok in this ticket and use the other for reference in push to not make lot of notification to you for test.

Thank's.

**Comment by tikismoke** [comment]
Could you have a new look to try a build, it works now on Travis.

How about signing the package? how does it works on f-droid?

**Comment by krt16s** [comment]
This looks buildable. Could you remove support-v4 and jeromq jar files and replace them with something like

````
dependencies {
    compile "com.android.support:support-v4:x.x.x"
    compile 'org.zeromq:jeromq:0.3.4'
}
````

in this gradle file as explained in https://developer.android.com/tools/support-library/setup.html (replacing x.x.x with the actual used version)?

Also, there seem to be many forks and versions of achartengine, which one did you use?

Signing: F-Droid signs apps with it's own unique app-specific key on default. Theoretically we support using upstream signatures, when we manage to produce bit-identical versions: We download upstream release, remove signature, compare the apk against what we have build and if they are identical, we use original upstream package, signed by upstream. But getting builds reproducible and bit-identical is a hard and lengthy task...

**Comment by krt16s** [comment]
FYI, this is the build scrip I currently use and which successfully builds the app:

````
Build:1.4,15
    commit=0b79c85d90386184a6f1f3e0a64e103438e78214
    subdir=Domodroid
    gradle=yes
    rm=Domodroid/libs/jeromq-0.3.4.jar,Domodroid/libs/android-support-v4.jar
    prebuild=sed -i -e '/existe plus/d' src/main/java/database/DomodroidDB.java && \
        sed -i -e '/compile fileTree/acompile "com.android.support:support-v4:23.0.1"\ncompile "org.zeromq:jeromq:0.3.4"\n' build.gradle
````

I will have a look at achartengine this weekend.

**Comment by tikismoke** [comment]
Ok nice to here.
For achartengine this is a direct link to it license https://github.com/ddanny/achartengine/blob/master/LICENSE-2.0.txt

**Comment by tikismoke** [comment]
For achatengine don't worry too much as I planned to moved to mpandroidchart #89

**Comment by krt16s** [comment]
This specific issues has been resolved, closing.

F-Droid availability: I added a build to the queue, bu when finished it will not show up in the main repo, but will be pushed directly to the archive. I will then ask users to test the build , since I don't have the server part running here. If everything works fine, it should be available monday/tuesday in the main repo.
