### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by krt16s** [domogik/domodroid#83]
You should add a LICENSE or COPYING file or just state the license used in the readme. If you haven't thought about a license, please keep in mind that the common GPLv2 is incompatible with Android's Apache2 licensed support libraries. GPLv2 adding the "and any later version"  fixes this.

**Comment by tikismoke** [comment]
It is indeed in GPL3 as notice in lot of files.

I'm updating the Readme.

**Comment by tikismoke** [comment]
Will be merge to master when releasing next version.

And i need to make sure it's include also in the apps (in About view or something like that).
